datasource:
    name: species
    username: ${SPECIES_DATABASE_USER}
    password: ${SPECIES_DATABASE_PASSWORD}
    url: jdbc:postgresql://${SPECIES_DATABASE_HOST}:${SPECIES_DATABASE_PORT}/${SPECIES_DATABASE_NAME}
    driver-class-name: org.postgresql.Driver
